apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test-documentation"
  description: "testing documentation template"
  annotations:
    github.com/project-slug: "diliprenkila/doc-test"
    backstage.io/techdocs-ref: github:https://github.com/diliprenkila/doc-test
spec:
  type: documentation
  lifecycle: experimental
  owner: "diliprenkila"
